In [1]:
import numpy as np
import pandas as pd

Pandas version

In [2]:
pd.__version__

'2.3.1'

Q2. Records count

In [6]:
df = pd.read_csv("car_fuel_efficiency.csv")
print(len(df))

9704


Q3. Fuel Types

In [94]:
fuel_type_num =df.fuel_type.nunique()
print(fuel_type_num)

2


Q4. Missing Values

In [13]:
missing_content = df.isnull().any().sum()
print(missing_content)

4


Q5. Max Fuel Efficiency

In [95]:
max_fuel_asia = df[df.origin == 'Asia']["fuel_efficiency_mpg"].max()
print(max_fuel_asia)

23.759122836520497


Q6. Median Value of Horsepower

In [96]:
median_hp = df.horsepower.median()
print(median_hp)

149.0


In [98]:
most_frequent = df["horsepower"].mode()
print(most_frequent)

0    152.0
Name: horsepower, dtype: float64


In [29]:
new_median = df['horsepower'].fillna(152).median()
print(new_median)

152.0


Q7. Sum of weights

In [40]:
Asia_cars = df[df["origin"] == "Asia"]
print(Asia_cars)

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front

In [62]:
Asia_cars_weight_modyear = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
print(Asia_cars_weight_modyear)

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]


In [64]:
Asia_cars_weight_modyear = df[df["origin"] == "Asia"][['vehicle_weight', 'model_year']].head(n=7)
print(Asia_cars_weight_modyear)

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019


In [80]:
X = Asia_cars_weight_modyear.values
print(X)

[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]


In [79]:
XT = X.T
print(XT)

[[2714.21930965 2783.86897424 3582.68736772 2231.8081416  2659.43145076
  2844.22753389 3761.99403819]
 [2016.         2010.         2007.         2011.         2016.
  2014.         2019.        ]]


In [89]:
XTX = XT.dot(X)
print(XTX)

[[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]


In [90]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [91]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [92]:
w = XTX_inv.dot(XT).dot(y)
w

array([0.01386421, 0.5049067 ])

In [93]:
w.sum()

np.float64(0.5187709081074016)