Vector Operations

In [1]:
import numpy as np

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
u

array([2, 4, 5, 6])

In [3]:
v = np.array([1, 0, 0, 2])

In [4]:
u + v

array([3, 4, 5, 8])

In [5]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0

    for i in range(n):
        result = result + (u[i] * v[i])
    
    return result

In [7]:
vector_vector_multiplication(u, v)

np.int64(14)

In [9]:
v.dot(u)
u.dot(v)

np.int64(14)

In [10]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [11]:
w = np.array([1, 0.5, 2, 1])

In [12]:
U.shape

(3, 4)

In [13]:
w.shape

(4,)

In [14]:
def matrix_vector_multiplication(U, w):
    assert U.shape[1] == w.shape[0]
    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], w)

    return result

In [17]:
y = matrix_vector_multiplication(U, w)
y

array([20. ,  6. ,  8.5])

In [19]:
y.shape

(3,)

In [21]:
U.dot(w)

array([20. ,  6. ,  8.5])

MATRIX-MATRIX MULTIPLICATION

In [ ]:
U = np.array

In [2]:
def matrix_matrix_multiplication(X, Y):
    assert X.shape[1] == Y.shape[0]
    num_row = X.shape[0]
    num_col = Y.shape[1]
    result = np.zeros((num_row, num_col))

    for i in range(num_col):
        yi = Y[:, i]        # Take the i-th column of matrix Y
        Xyi = matrix_vector_multiplication(X, yi)   # Multiply matrix X by vector yi
        result[:, i] = Xyi      # Set the i-th column of the result matrix
    return result