In [2]:
import numpy as np

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
# Creating arrays
# You can only have np.zeros and np.ones. You cant have twos, threes, etc

In [7]:
np.ones(2)

array([1., 1.])

In [14]:
np.full(3, 4)

array([4, 4, 4])

In [16]:
a = np.array([1,2,3,4,5]) #This is how you convert a list to an array

In [17]:
a

array([1, 2, 3, 4, 5])

In [21]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [25]:
print(a[4])

5


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 100, 6)   # This creates an array with the size using the start and finish specified

array([  0.,  20.,  40.,  60.,  80., 100.])

Multidimensional Arrays

In [15]:
np.zeros((5,2))     # create array with 5 rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
b[0, 0]     # accessing the elements
b[0, 1] = 20
b

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
print(b[0])        # Accessing only rows
print (b[1])

[ 1 20  3]
[4 5 6]


In [28]:
# Accessing only Columns

print(b[:, 0])
print(b[:, 1])

[1 4 7]
[20  5  8]


Randomly Generated Arrays

In [30]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [31]:
np.random.randint(low=0, high=10, size=(3, 4))

array([[4, 5, 7, 3],
       [6, 4, 3, 7],
       [6, 1, 3, 5]])

Element-wise Operation

In [3]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [12]:
c + 1       # This adds 1 to all elements of the array
c * 2
d = (10 + (c * 2)) ** 2
d

array([100, 144, 196, 256, 324])

In [13]:
c + d

array([100, 145, 198, 259, 328])

Comparison Operations

In [14]:
c

array([0, 1, 2, 3, 4])

In [18]:
c >= 2      # this checks which element is greater/equal to 2
c > d

array([False, False, False, False, False])

Summarizing Operations

In [11]:
c.min()     # Shows the min number in the array
c.max()
c.sum()
c.mean()
c.std()

np.float64(1.4142135623730951)